
```{r,message=FALSE}
library(tidyverse)
library(ggplot2)
data <- read.csv("C:/Users/jeong/iCloudDrive/Graphics data/data_daRjo.csv")

rain <- read.csv("C:/Users/jeong/iCloudDrive/Graphics data/2022_rain.csv")

temp <- read.csv("C:/yunju/TEMP/TEMP2024/graphics/project/2022_weather.csv")

rain[is.na(rain)] <- 0
temp[is.na(temp)] <- 26.8
```

```{r}
data <- data %>% select(-max, -min, -average, -gap, -avg_max, -avg_min)
temp$date <- sub("^\\s+", "", temp$date)
rain = rain %>% separate(date, into=c("year","month","day"),convert=TRUE)
temp = temp %>% separate(date, into=c("year","month","day"),convert=TRUE)
```

```{r}
data <- data %>% left_join(rain) %>% left_join(temp)
```

```{r}
library(tidyverse)

data = data %>%
  mutate(fine_dust_level = case_when(
    fine.dust <= 15 ~ "good",
    fine.dust <= 35 ~ "so so",
    fine.dust <= 75 ~ "bad",
    TRUE ~ "worst"), 
    )
```

```{r}
dim(data)[1]

data = data %>%
  mutate(
    fine_dust_level = factor(fine_dust_level, levels = c("worst", "bad", "so so", "good"))
  )


data %>% group_by(fine_dust_level) %>% count() %>% mutate(ratio = n/571756) %>% ggplot(aes(fine_dust_level,ratio)) + geom_bar(stat="identity")
```

```{r}
total_days <- data %>%
  group_by(year, month, day, fine_dust_level) %>% 
  summarise(count = n(), .groups = "drop") %>%   
  group_by(fine_dust_level) %>%                  
  summarise(total_days = n(), .groups = "drop")

total_days

total_days %>% ggplot(aes(fine_dust_level,total_days)) + geom_bar(stat="identity")
```

```{r}
data %>% 
  group_by(fine_dust_level) %>% 
  summarise(count=n()) %>% 
  left_join(total_days) %>% 
  mutate(ratio = count/total_days) %>% 
  ggplot(aes(fine_dust_level,ratio)) + 
  geom_bar(stat="identity")
```

```{r}
data_worst <- data %>% 
  filter(fine_dust_level=="worst") %>% 
  group_by(year,month,day,distinct) %>% 
  summarise(count=n(),                                                                        average_ = mean(average),
            rain = mean(rainfall))

data_worst

## 강수량이 5mm 이상인 날의 비율
dim(data_worst %>%  filter(rain>5)) [1] / dim(data_worst)[1]
```

```{r}
data_bad <- data %>% 
  filter(fine_dust_level=="bad") %>% 
  group_by(year,month,day,distinct) %>% 
  summarise(count=n(),                                                                        average_ = mean(average),
            rain = mean(rainfall))

data_bad

## 강수량이 5mm 이상인 날의 비율
dim(data_bad %>%  filter(rain>5)) [1] / dim(data_bad)[1]
```

-   fine_dust_level이 bad인 경우 -\> 강수량이 0이기 때문에 따릉이 사용량이 많은 것으로 예측할 수 있음

```{r}
data_so <- data %>% 
  filter(fine_dust_level=="so so") %>% 
  group_by(year,month,day,distinct) %>% 
  summarise(count=n(),                                                                        average_ = mean(average),
            rain = mean(rainfall))

head(data_so)

## 강수량이 5mm 이상인 날의 비율
dim(data_so %>%  filter(rain>5)) [1] / dim(data_so)[1]
```

```{r}
data_good <- data %>% 
  filter(fine_dust_level=="good") %>% 
  group_by(year,month,day,distinct) %>% 
  summarise(count=n(),                                                                        average_ = mean(average),
            rain = mean(rainfall))

head(data_good)
## 강수량이 5mm 이상인 날의 비율
dim(data_good %>%  filter(rain>5)) [1] / dim(data_good)[1]
```

-   fine_dust_level이 good인 경우, 다른 level에 비해 비가 오는 날이 많아 비교적 따릉이 사용량이 적게 나타나는 것으로 예측할 수 있음

```{r}
data_winter <- read.csv("C:/Users/jeong/iCloudDrive/Graphics data/data_winter.csv")

head(data_winter)

data_winter$date = as.Date(data_winter$date)
head(data_winter)
```

```{r}
## 기타 -> NA로 바꾸기 
data_winter <- data_winter %>%
  mutate(age = ifelse(age == "기타", NA, age))

data_winter <- data_winter %>% filter(!is.na(data_winter$date))
```

```{r}
summary(data_winter)
```

```{r}
sum(is.na(data_winter$age))
```

```{r}
data_winter %>% group_by(date) %>% 
  summarise(n=n()) %>% 
  ggplot(aes(date,n)) + geom_line()
```

-   data_winter 기온

```{r}
data_winter %>% group_by(date) %>%
  summarise(gap = mean(temp_gap),
            avg = mean(temp_avg),
            max = mean(temp_max),
            min = mean(temp_min)) %>%
  ggplot() + 
  geom_line(aes(date,min), color="blue") + 
  geom_line(aes(date,max), color="red") + 
  geom_line(aes(date,avg))
```

```{r}
data_winter %>% group_by(date) %>%
  summarise(temp_max = mean(temp_max,na.rm=TRUE)) %>%
            filter(temp_max>20) %>% arrange(desc(temp_max))



## peak -> 10/15, 11/11, 11/12
```

-   일교차 분포, outlier

```{r}
data_winter %>%
  group_by(date) %>%
  summarise(gap=mean(temp_gap)) %>% 
  ggplot(aes(gap)) + geom_histogram(binwidth=0.5)

data_winter %>%
  group_by(date) %>%
  summarise(gap=mean(temp_gap)) %>% 
  ggplot(aes(gap)) + geom_histogram(binwidth=0.25)


data_winter %>%
  group_by(date) %>%
  summarise(gap=mean(temp_gap)) %>%
  filter(gap>16)
```

-   일교차에 따른 따릉이 사용량 변화

```{r}
data_winter %>%
  group_by(date) %>%
  summarise(count=n(),gap=mean(temp_gap)) %>%
  ggplot(aes(gap,count)) + geom_point() + geom_smooth(method='lm') + xlim(4,15)
```

```{r}
data_gap <- data_winter %>%
  group_by(date) %>%
  summarise(count=n(),gap=mean(temp_gap)) %>%
  filter(gap<16)


result <- cor.test(data_gap$count, data_gap$gap)
print(result)
```

-   평균 기온에 따른 따릉이 사용량 변화

```{r}
data_winter %>% group_by(date) %>%
  summarise(n=n(),
            avg = mean(temp_avg)) %>%
  ggplot(aes(n,avg)) + geom_point()
```

```{r}
data_avg <- data_winter %>%
  group_by(date) %>%
  summarise(count=n(),avg=mean(temp_avg))


result <- cor.test(data_avg$count, data_avg$avg)
print(result)
```

```{r}
data <- data %>% 
  rename(temp_avg = average)
```

```{r}
data_avg <- data %>% 
  mutate(date = as.Date(paste(year,month,day,sep="-"))) %>%
  select(date,temp_avg)
  
  
data_winter_avg <- data_winter %>% select(date, temp_avg)

temp_avg <- rbind(data_avg, data_winter_avg)
```

```{r}
temp_avg <- temp_avg %>% group_by(date) %>%
  summarise(count=n(), temp_avg = mean(temp_avg)) %>%
  mutate(season = case_when(
    temp_avg <= 10 ~ "winter",
    temp_avg <= 23 ~ "fall",
    TRUE ~ "summer"))
```

```{r}
data_winter_avg %>% group_by(date) %>%
  summarise(count=n(), temp_avg = mean(temp_avg)) %>%
  mutate(season = case_when(
    temp_avg <= 10 ~ "winter",
    temp_avg <= 23 ~ "fall",
    TRUE ~ "summer")) %>% ggplot(aes(count, temp_avg)) + geom_point(aes(color=season))
```

```{r}
ggplot(temp_avg,aes(count, temp_avg)) + geom_point(aes(color=season))

temp_avg %>% filter(count<5000)
```

```{r}
temp_avg[temp_avg$count<15000,]  ## 8월 1일 - 9월 30일 , 10월 3일

temp_avg[temp_avg$count>15000,]  ## 10월 1일 - 12월 31일
```

-   distance

```{r}
data_winter %>% ggplot(aes(distance)) + geom_freqpoly(binwidth=10) + scale_x_continuous(labels = scales::comma) + scale_y_continuous(labels = scales::comma) + xlim(0,100000)
```

```{r}
summary(data_winter$distance)
```

-   자전거 속력 60부터 말이 안 돼

10-30km/h

-\> 30000m/h

-\>500m/m

```{r}
data_winter <- data_winter %>% mutate(velocity = ifelse(time == 0, NA, distance / time), na.rm=TRUE)

head(data_winter[is.na(data_winter$velocity),])
```

```{r}
summary(data_winter$time)
```

```{r}
data_filtered <- data_winter %>% filter(velocity<500, 170<velocity)

data_filtered %>% ggplot(aes(distance)) + geom_freqpoly() + scale_x_continuous(labels = scales::comma) + scale_y_continuous(labels = scales::comma)

```

```{r}
summary(data_filtered$distance)

head(data_filtered[(data_filtered$distance) < (440+(440-253.1)*1.5),])
```

```{r}
data_winter %>% filter(velocity<500) %>% ggplot(aes(distance)) + geom_boxplot() + scale_x_continuous(labels = scales::comma) + scale_y_continuous(labels = scales::comma) + coord_flip()
```

```{r}
data <- data %>% select(-fine_dust_level)
```

```{r}
data<- data %>%mutate(
  date = as.Date(paste(year,month,day,sep="-")),
  rent_office_number = as.factor(rent_office_number),
  age = as.factor(age),
  distinct = as.factor(distinct)
) %>% select(-year,-month,-day)

head(data)
summary(data)

```

```{r}
data %>% ggplot(aes(date,temp_avg)) + geom_line()
```

```{r}
data %>% mutate(
                 weekday = weekdays(date, abbreviate=TRUE),
                 weekday = factor(weekday, levels=c("일","월","화","수","목","금","토")),
                 month = as.numeric(date-as.Date("2022-07-31"))%/%31+8) %>%
  group_by(month,weekday) %>%
  count() %>% 
  ggplot(aes(weekday,n,group=month,color=factor(month))) +
  geom_line()
```

```{r}
data %>% mutate(
                 weekday = weekdays(date, abbreviate=TRUE),
                 weekday = factor(weekday, levels=c("일","월","화","수","목","금","토")),
                 month = as.numeric(date-as.Date("2022-07-31"))%/%31+8) %>% 
  filter(month == 8, weekday == "화") %>% 
  group_by(date) %>% summarise(
    fine.dust = mean(fine.dust),
    temp_avg = mean(temp_avg),
    rainfall = mean(rainfall)
  )
```

```{r}
data_winter <- read.csv("C:/Users/jeong/iCloudDrive/Graphics data/winterdata.csv")
```

```{r}
data_winter <- data_winter %>% select(-weekday)
```

```{r}
data_winter <- data_winter %>% mutate(
  rent_office_number = as.factor(rent_office_number),
  age = as.factor(age),
  exercise = as.integer(exercise),
  carbon = as.integer(carbon),
  date = as.Date(date)
)
```

```{r}
summary(data_winter)
```

```{r, message=FALSE}
library(GGally)
```

```{r}
#ggpairs(data_winter[8:14])
```

```{r}
range(data_winter$temp_avg)

data_winter %>% ggplot(aes(x=cut_width(temp_avg,2),y=exercise)) + geom_bar(stat="identity") + xlab("temp_avg")
```

```{r}
data_winter %>% group_by(date) %>%
  summarise(exercise_mean = mean(exercise, na.rm=TRUE),
            distance_mean = mean(distance,na.rm=TRUE),
            n = n()) %>% ggplot(aes(exercise_mean, distance_mean)) + geom_point()
  
```

```{r}
peak_date <- as.Date(c("2022-10-15","2022-11-11","2022-11-12"))

data_winter %>% filter(date %in% peak_date) %>%
  group_by(date) %>%
  summarise(
    exercise=mean(exercise,na.rm=TRUE), carbon=mean(carbon,na.rm=TRUE),
    distance = mean(distance), time = mean(time), temp_avg = mean(temp_avg),
    temp_max = mean(temp_max), temp_min = mean(temp_min), temp_gap = mean(temp_gap),
    fine.dust = mean(fine.dust), rainfall = mean(rainfall)
  )
```

```{r}
data_winter %>% mutate(
                 weekday = weekdays(date, abbreviate=TRUE),
                 weekday = factor(weekday, levels=c("일","월","화","수","목","금","토")),
                 month = as.numeric(date-as.Date("2022-07-31"))%/%31+8) %>%
  group_by(month,weekday) %>%
  count() %>% 
  ggplot(aes(weekday,n,group=month,color=factor(month))) +
  geom_line()
```

```{r}
data_winter %>% mutate(
                 weekday = weekdays(date, abbreviate=TRUE),
                 weekday = factor(weekday, levels=c("일","월","화","수","목","금","토")),
                 month = as.numeric(date-as.Date("2022-07-31"))%/%31+8) %>% 
  filter(month == 10, weekday=="토") %>%
  group_by(date) %>% summarise(
    fine.dust = mean(fine.dust),
    temp_avg = mean(temp_avg),
    rainfall = mean(rainfall)
  )
```

```{r}
data_winter %>% mutate(
                 weekday = weekdays(date, abbreviate=TRUE),
                 weekday = factor(weekday, levels=c("일","월","화","수","목","금","토")),
                 month = as.numeric(date-as.Date("2022-07-31"))%/%31+8) %>% 
  filter(month == 10) %>% group_by(date) %>%
  summarise(rainfall = mean(rainfall),
            temp_avg = mean(temp_avg))
```

```{r}
data_winter %>% mutate(
                 weekday = weekdays(date, abbreviate=TRUE),
                 weekday = factor(weekday, levels=c("일","월","화","수","목","금","토")),
                 month = as.numeric(date-as.Date("2022-07-31"))%/%31+8) %>% 
  filter(month == 10) %>% group_by(weekday) %>%
  summarise(mean = mean(temp_avg),
            max = mean(temp_max),
            min = mean(temp_min)) 
```
